/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.socialvagrancy.taskmanager.client.ui.component;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author seans
 */
public class CalendarPopup extends javax.swing.JFrame {

    /**
     * Creates new form CalendarPopup
     */
    public CalendarPopup(ActionListener parent_listener, String format) {
        initComponents();
        
        button_listener = parent_listener;
        date_format = DateTimeFormatter.ofPattern(format);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calendarPanel1 = new com.github.lgooddatepicker.components.CalendarPanel();
        button_panel = new javax.swing.JPanel();
        select_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(calendarPanel1, java.awt.BorderLayout.CENTER);

        select_button.setText("Ok");
        select_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_buttonActionPerformed(evt);
            }
        });
        button_panel.add(select_button);

        cancel_button.setText("Cancel");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });
        button_panel.add(cancel_button);

        getContentPane().add(button_panel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void select_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_buttonActionPerformed
        String selected_date = calendarPanel1.getSelectedDate().format(date_format);
        
        ActionEvent current_date = new ActionEvent(select_button, 0, selected_date);
        
        button_listener.actionPerformed(current_date);
        
        toggleCalendar();
    }//GEN-LAST:event_select_buttonActionPerformed

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        toggleCalendar();
    }//GEN-LAST:event_cancel_buttonActionPerformed

    public void toggleCalendar()
    {
        setVisible(!isVisible());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel button_panel;
    private com.github.lgooddatepicker.components.CalendarPanel calendarPanel1;
    private javax.swing.JButton cancel_button;
    private javax.swing.JButton select_button;
    // End of variables declaration//GEN-END:variables
    private DateTimeFormatter date_format;
    private ActionListener button_listener;
}
