/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.socialvagrancy.taskmanager.client.ui;

import com.socialvagrancy.taskmanager.client.command.GetTasks;
import com.socialvagrancy.taskmanager.client.ui.Controller;
import com.socialvagrancy.taskmanager.structure.Contact;
import com.socialvagrancy.taskmanager.structure.Task;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 *
 * @author seans
 */
public class TaskList extends javax.swing.JPanel implements Screen {

    /**
     * Creates new form TaskList
     */
    public TaskList() {
        initComponents();
        task_date_picker.setDateToToday();
        search_button.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                refresh(null); // Null refresh as no id is required.
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        overview_pane = new javax.swing.JPanel();
        owner_selector = new javax.swing.JComboBox<>();
        search_button = new javax.swing.JButton();
        owner_label = new javax.swing.JLabel();
        date_label = new javax.swing.JLabel();
        task_date_picker = new com.github.lgooddatepicker.components.DatePicker();
        new_task_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        task_list = new javax.swing.JTextArea();
        jScrollBar1 = new javax.swing.JScrollBar();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Task Details"));

        overview_pane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        owner_selector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        search_button.setText("Search");
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });

        owner_label.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        owner_label.setText("Belongs To:");

        date_label.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        date_label.setText("Task Date:");

        new_task_button.setText("New");

        javax.swing.GroupLayout overview_paneLayout = new javax.swing.GroupLayout(overview_pane);
        overview_pane.setLayout(overview_paneLayout);
        overview_paneLayout.setHorizontalGroup(
            overview_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overview_paneLayout.createSequentialGroup()
                .addGroup(overview_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(overview_paneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(overview_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(overview_paneLayout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(date_label))
                            .addGroup(overview_paneLayout.createSequentialGroup()
                                .addComponent(new_task_button)
                                .addGap(8, 8, 8)
                                .addComponent(task_date_picker, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(search_button))))
                    .addGroup(overview_paneLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(owner_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(owner_selector, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        overview_paneLayout.setVerticalGroup(
            overview_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overview_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(overview_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(task_date_picker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(new_task_button)
                    .addComponent(search_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(overview_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(owner_selector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(owner_label))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        task_list.setColumns(20);
        task_list.setRows(5);
        jScrollPane1.setViewportView(task_list);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(overview_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(overview_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_search_buttonActionPerformed

    @Override
    public void refresh(String id)
    { 
        // Ignore the ID code
        // Using the screen interface which defines and item id.
        
        // Reset the task owner selector box
        // This needs to be completed first before querying for tasks
        // otherwise we search for the default "Item 1"
        ArrayList<Contact> user_list = api_controller.getUsers();
        owner_selector.removeAllItems();
        
        for(int i=0; i<user_list.size(); i++)
        {
            owner_selector.addItem(user_list.get(i).fullName());
        }
    
        ArrayList<Task> task_list = api_controller.getTasks(task_date_picker.toString(), owner_selector.getSelectedItem().toString());
        
        this.revalidate();
        this.repaint();
    }

    @Override
    public void setApiController(Controller api)
    {
        api_controller = api;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date_label;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton new_task_button;
    private javax.swing.JPanel overview_pane;
    private javax.swing.JLabel owner_label;
    private javax.swing.JComboBox<String> owner_selector;
    private javax.swing.JButton search_button;
    private com.github.lgooddatepicker.components.DatePicker task_date_picker;
    private javax.swing.JTextArea task_list;
    // End of variables declaration//GEN-END:variables

    private Controller api_controller;
}
